{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp-watcher.secretName" . }}
  labels:
    {{- include "sftp-watcher.labels" . | nindent 4 }}
type: Opaque
stringData:
  SFTP_PASSWORD: {{ .Values.secret.sftpPassword | quote }}
  AAP_TOKEN: {{ .Values.secret.aapToken | quote }}
{{- end }}
